### ISSUE TITLE
Add support to pipe tap output to other reporter

### ISSUE THREAD

**Issue by LabiKyo** [conradz/tap-webpack-plugin#4] opened 2016-03-21 05:50 UTC
Hi, thanks for this great plugin.

I read the source code, saw your usage of `tap-out` and process errors by hand. Why not just pipe out tap output and let the developer decide which [reporter](https://github.com/substack/tape#pretty-reporters) to use? I think it's much more flexible.

I would like to make a pull request if you're ok with this feature.

**Comment by conradz** [comment] 2016-03-21 12:26
The problem is that webpack has other (non-tap) output, such as a listing of chunks, and listing of syntax errors or errors with other loaders or plugins. Piping the output of webpack directly into a tap reporter would result in it being broken when there is additional output.

#3 has a fix for this by directly piping only the TAP output into a reporter, but is still somewhat incomplete. That is the route that seems the most promising.

**Comment by LabiKyo** [comment] 2016-03-22 02:38
Cool. I checked the pull request. So the only problem left now is the color being stripped? I'd like to help since I need this feature myself.

**Comment by conradz** [comment] 2016-03-22 21:03
Added to v1.1.0, see the docs in the readme for the `reporter` option.

**Closed as completed by conradz** 2016-03-22 21:03 UTC
