### ISSUE TITLE
Does not report test success to console 

### ISSUE THREAD

**Issue by mpj** [conradz/tap-webpack-plugin#2] opened 2015-12-14 17:25 UTC

**Comment by conradz** [comment] 2015-12-14 19:00
This behaves as a normal webpack plugin, it does not log anything unless there was an error. If there is an error it will display the error as a normal webpack error.

**Comment by conradz** [comment] 2015-12-24 13:50
Closing this as I'm not sure exactly what you are proposing. It is currently by design not to log anything to the console on success, if you have any suggestions of what it should do feel free to re-open.

**Closed as completed by conradz** 2015-12-24 13:50 UTC

**Comment by ArtemZag** [comment] 2016-11-14 10:16
Is it possible to add plugin optional parameter?
Like this:
`new TapWebPackPlugin({ outputSuccededTests: true })`

Or like this:
`new TapWebPackPlugin({ showTapeOutput: true })`
